services:
  dagster:
    user: "${UID}:${GID}"
    environment:
      ADIT_AUTH_TOKEN: "${ADIT_AUTH_TOKEN}"
      ADIT_HOST: "${ADIT_HOST}"
      CA_BUNDLE: "${CA_BUNDLE}"
      DAGSTER_HOME: "/opt/dagster/dagster_home"
      HTTP_PROXY: "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTPS_PROXY}"
      INSTITUTION_ADDRESS_REGEX: "${INSTITUTION_ADDRESS_REGEX}"
      INSTITUTION_NAME_REGEX: "${INSTITUTION_NAME_REGEX}"
      MIN_VOLUME_SIZE: "${MIN_VOLUME_SIZE}"
      MODALITIES: "${MODALITIES}"
      NO_PROXY: "${NO_PROXY}"
      PACS_AE_TITLE: "${PACS_AE_TITLE}"
    command: >
      bash -c "./scripts/start_server.sh"
