services:
  dagster:
    build:
      target: development
    image: export_volumes_pipeline_dev:latest
    ports:
      - "${DAGSTER_DEV_PORT:-3500}:3000"
    volumes:
      - ./dagster_home_dev:/opt/dagster/dagster_home
      - .:/opt/dagster/app
