services:
  dagster:
    build:
      target: production
    image: export_volumes_pipeline_prod:latest
    volumes:
      - ./dagster_home_prod:/opt/dagster/dagster_home
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "${WEB_HTTP_PORT:-80}:80"
      - "${WEB_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./env/.htpasswd:/etc/nginx/.htpasswd
      - ./env/ssl.crt:/etc/nginx/ssl.crt
      - ./env/ssl.key:/etc/nginx/ssl.key
    depends_on:
      - dagster
    command:
    restart: always

volumes:
  nginx_data:
