services:
  dagster:
    build:
      target: development
    image: export_volumes_pipeline_dev:latest
    ports:
      - "${WEB_HTTP_PORT:-80}:80"
      - "${WEB_HTTPS_PORT:-443}:443"
    volumes:
      - ./dagster_home_dev:/opt/dagster/dagster_home
      - .:/opt/dagster/app
